In [1]:
# installing the libraries
!pip install numpy
!pip install pandas

Collecting numpy
  Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 1.0 MB/s eta 0:00:12
   - -------------------------------------- 0.5/12.3 MB 1.0 MB/s eta 0:00:12
   -- ------------------------------------- 0.8/12.3 MB 859.7 kB/s eta 0:00:14
   --- ------------------------------------ 1.0/12.3 MB 936.0 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.3 MB 887.6 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.3 MB 887.6 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/12.3 MB 909.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/12.3 MB 909.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.8/12.3 MB 835.4 kB/s eta 0:00:13
   ------ --------------------------------- 2.1/12.3 MB 854.8 kB/s eta 0:00:12
   ------- -------------------------------- 2.4/12.3 MB 872.1 kB/s eta 0:00:12
   ------- -------------------------------- 2.4/12.3 MB 872.1 kB/s eta 0:00:12
   -------- ------------------------------- 2.6/12.3 MB 836.5 kB/s eta 0:00:12
   -------- ------------------------------- 2.6/12.3 MB 836.5 kB/s eta 0:00:12
   -------- ------------------------------- 2.6/12.3 MB 836.5 kB/s eta 0:00:12
   --------- ------------------------------ 2.9/12.3 MB 785.1 kB/s eta 0:00:13
   ---------- ----------------------------- 3.1/12.3 MB 780.7 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/12.3 MB 780.7 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/12.3 MB 780.7 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/12.3 MB 756.9 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/12.3 MB 756.9 kB/s eta 0:00:12
   ----------- ---------------------------- 3.7/12.3 MB 744.6 kB/s eta 0:00:12
   ----------- ---------------------------- 3.7/12.3 MB 744.6 kB/s eta 0:00:12
   ------------ --------------------------- 3.9/12.3 MB 735.2 kB/s eta 0:00:12
   ------------ --------------------------- 3.9/12.3 MB 735.2 kB/s eta 0:00:12
   ------------- -------------------------- 4.2/12.3 MB 730.2 kB/s eta 0:00:12
   ------------- -------------------------- 4.2/12.3 MB 730.2 kB/s eta 0:00:12
   -------------- ------------------------- 4.5/12.3 MB 708.7 kB/s eta 0:00:12
   -------------- ------------------------- 4.5/12.3 MB 708.7 kB/s eta 0:00:12
   --------------- ------------------------ 4.7/12.3 MB 716.7 kB/s eta 0:00:11
   ---------------- ----------------------- 5.0/12.3 MB 725.8 kB/s eta 0:00:11
   ---------------- ----------------------- 5.0/12.3 MB 725.8 kB/s eta 0:00:11
   ----------------- ---------------------- 5.2/12.3 MB 728.1 kB/s eta 0:00:10
   ----------------- ---------------------- 5.5/12.3 MB 736.1 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.3 MB 741.9 kB/s eta 0:00:09
   ------------------- -------------------- 6.0/12.3 MB 753.6 kB/s eta 0:00:09
   ------------------- -------------------- 6.0/12.3 MB 753.6 kB/s eta 0:00:09
   -------------------- ------------------- 6.3/12.3 MB 765.4 kB/s eta 0:00:08
   --------------------- ------------------ 6.6/12.3 MB 777.2 kB/s eta 0:00:08
   ---------------------- ----------------- 6.8/12.3 MB 783.5 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.3 MB 792.8 kB/s eta 0:00:07
   ----------------------- ---------------- 7.3/12.3 MB 800.2 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.3 MB 808.2 kB/s eta 0:00:06
   ------------------------- -------------- 7.9/12.3 MB 818.5 kB/s eta 0:00:06
   -------------------------- ------------- 8.1/12.3 MB 822.6 kB/s eta 0:00:06
   -------------------------- ------------- 8.1/12.3 MB 822.6 kB/s eta 0:00:06
   --------------------------- ------------ 8.4/12.3 MB 829.7 kB/s eta 0:00:05
   ---------------------------- ----------- 8.7/12.3 MB 833.8 kB/s eta 0:00:05
   ---------------------------- ----------- 8.9/12.3 MB 841.6 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.3 MB 849.1 kB/s eta 0:00:04
   ------------------------------ --------- 9.4/12.3 MB 852.7 kB/s eta 0:00:04
   ------------------------------- -------- 9.7/12.3 MB 858.1 kB/s eta 0:00:04
   -------------------------------- ------- 10.0/12.3 MB 866.4 kB/s eta 0:00:03
   --------------------------------- ------ 10.2/12.3 MB 873.6 kB/s eta 0:00:03
   ---------------------------------- ----- 10.5/12.3 MB 880.1 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.3 MB 885.9 kB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.3 MB 885.9 kB/s eta 0:00:02
   ----------------------------------- ---- 11.0/12.3 MB 889.9 kB/s eta 0:00:02
   ------------------------------------- -- 11.5/12.3 MB 902.9 kB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 909.5 kB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 915.6 kB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 915.6 kB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 911.2 kB/s  0:00:13
Installing collected packages: numpy
Successfully installed numpy-2.4.4

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in d:\python_projects\ml\laptop price predictor\.venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\python_projects\ml\laptop price predictor\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\python_projects\ml\laptop price predictor\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 1.5 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/9.7 MB 1.9 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.7 MB 2.2 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.7 MB 2.3 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.7 MB 2.3 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.7 MB 2.3 MB/s eta 0:00:03
   ---------------- ----------------------- 3.9/9.7 MB 2.3 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.7 MB 2.3 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.7 MB 2.3 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.7 MB 2.3 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.7 MB 2.4 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.7 MB 2.4 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.7 MB 2.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.7 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 2.6 MB/s  0:00:03
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.2 tzdata-2026.2

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
%pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in d:\python_projects\ml\laptop price predictor\.venv\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# importing the necessary libraries
import numpy as np 
import pandas as pd

In [3]:
# read the csv file 
# Tell the pandas to read the special characters as latin1 through encoding
data = pd.read_csv('laptop_price.csv',encoding='latin1')

In [4]:
# checkign the sample data 
data.sample(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
1179,1197,HP,ProBook 450,Notebook,15.6,1366x768,Intel Core i3 6100U 2.3GHz,4GB,Intel HD Graphics 520,Windows 10,2.07kg,650.00
774,783,HP,EliteBook 820,Ultrabook,12.5,1366x768,Intel Core i5 6200U 2.3GHz,4GB,Intel HD Graphics 520,Windows 10,1.26kg,1244.00
628,635,Asus,Q304UA-BHI5T11 (i5-7200U/6GB/1TB/FHD/W10),2 in 1 Convertible,13.3,Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,6GB,Intel HD Graphics 620,Windows 10,1.5kg,639.01
418,425,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.14kg,539.95
889,900,Lenovo,IdeaPad 110-17ACL,Notebook,17.3,1600x900,AMD A4-Series 7210 2.2GHz,4GB,AMD Radeon R3,Windows 10,2.8kg,379.00
864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16GB,Intel Iris Plus Graphics 640,Windows 10,1.29kg,2240.00
948,962,Dell,Insprion 5767,Notebook,17.3,1600x900,Intel Core i3 6006U 2.0GHz,4GB,AMD Radeon R7 M445,Windows 10,2.36kg,659.00
710,718,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.5kg,1249.00
697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4GB,Intel HD Graphics 515,Chrome OS,1.2kg,669.00
955,969,Dell,Alienware 17,Gaming,17.3,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 1070,Windows 10,4.36kg,3154.00

In [171]:
# check the data types 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [5]:
# checking is there any null values  ?
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [6]:
# converting the Object type ram field into int type field and remove the GB part 
data['Ram'] = data['Ram'].astype('str')
data['Ram'] = data['Ram'].str.replace('GB','').astype('int32')
data['Ram']

0        8
1        8
2        8
3       16
4        8
        ..
1298     4
1299    16
1300     2
1301     6
1302     4
Name: Ram, Length: 1303, dtype: int32

In [ ]:
# converting the weight field into float field and remove the KG part 
data['Weight'] = data['Weight'].astype('str')
data['Weight'] = data['Weight'].str.replace('kg','').astype('float64')
data['Weight']

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298    1.80
1299    1.30
1300    1.50
1301    2.19
1302    2.20
Name: Weight, Length: 1303, dtype: float64

In [8]:
#find the correlation between laptopid , inches , ram , weight with Price_euros , and only take the numeric values 
data.corr(numeric_only=True)['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [9]:
#checking the categories- of company 
data['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [10]:
# categorizing the lower value coloumns into a one column as other 
other_companies = {'Samsung', 'Mediacom', 'Razer', 'Microsoft', 'Vero', 
                   'Xiaomi', 'Chuwi', 'Fujitsu', 'Google', 'LG', 'Huawei'}
data['Company'] = data['Company'].apply(lambda x :'other' if x in other_companies else x)
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [11]:
# checking the categories of product 
len(data['Product'].value_counts())

618

In [12]:
# checking the categories of Type name 
data['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [13]:
# checking the categories of Screen resolutions 
data['ScreenResolution'].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
IPS Panel 1366x768                                 7
Touchscreen 2560x1440                              7
4K Ultra HD 3840x2160                              7
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Touchscreen 2560x1440                    5
1440x900                                           4
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
IPS Panel 2560x1440                                4
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1366x768                     3
1920x1080                                          3
Quad HD+ 3200x1800                                 3
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Full HD 1366x768                         1
IPS Panel Full HD 2560x1440                        1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [14]:
# dividing the entire columns into 2 parts as IPS and Touchscreen 
data['Touchscreen'] = data['ScreenResolution'].apply(lambda x: 1 if 'Touchscreen' in x else 0 )
data['Ips'] = data['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)

In [15]:
# checking the categories of cpu 
data['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz              190
Intel Core i7 7700HQ 2.8GHz             146
Intel Core i7 7500U 2.7GHz              134
Intel Core i7 8550U 1.8GHz               73
Intel Core i5 8250U 1.6GHz               72
                                       ...
Intel Core i5 7200U 2.7GHz                1
Intel Pentium Dual Core 4405Y 1.5GHz      1
Intel Core M 6Y54 1.1GHz                  1
Samsung Cortex A72&A53 2.0GHz             1
AMD E-Series 9000 2.2GHz                  1
Name: count, Length: 118, dtype: int64

In [16]:
# only gettign the first 3 names of the cpu name column
data['Cpu_name'] = data['Cpu'].apply(lambda x:" ".join(x.split()[0:3]))
data['Cpu_name'].value_counts()

Cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
AMD A6-Series 9220            8
Intel Celeron Quad            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
Intel Atom x5-Z8550           4
AMD A8-Series 7410            4
AMD Ryzen 1700                3
Intel Pentium Dual            3
AMD A9-Series 9410            3
AMD E-Series E2-9000e         2
Intel Xeon E3-1505M           2
AMD A10-Series A10-9620P      2
AMD A6-Series A6-9220         2
AMD A10-Series 9600P          2
AMD A10-Series 9620P          2
AMD E-Series 7110             2
AMD A9-Series A9-9420         2
Intel Xeon E3-1535M           2
Intel Atom X5-Z8350           2
Intel Atom x5-Z8300           1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD E-Series 6110             1
AMD E-Series 9000e            1
AMD Ryzen 1600                1
AMD E-Series E2-9000          1
AMD A6-Series 7310            1
Intel Atom Z8350              1
AMD A12-Series 9700P          1
AMD A4-Series 7210            1
AMD FX 8800P                  1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
Name: count, dtype: int64

In [17]:
# dividie the cpu into categories 
data['Cpu_name'] = data['Cpu_name'].apply(
    lambda x: 'AMD' if 'AMD' in x 
    else 'intel core i7' if x == 'Intel Core i7' 
    else 'intel core i5' if x == 'Intel Core i5' 
    else 'intel core i3' if x == 'Intel Core i3' 
    else 'Other'
)

print(data['Cpu_name'].value_counts())

Cpu_name
intel core i7    527
intel core i5    423
Other            155
intel core i3    136
AMD               62
Name: count, dtype: int64

In [18]:
# checking the cateogaries  of GPU 
data['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
Nvidia Quadro M500M          1
AMD Radeon R7 M360           1
Nvidia Quadro M3000M         1
Nvidia GeForce 960M          1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [19]:
# Divide the GPU into categories 
data['GPU_Name'] = data['Gpu'].apply(lambda x:'Intel' if 'Intel' in x 
                                    else 'Nvidia' if 'Nvidia' in x
                                    else 'AMD' if 'AMD' in x 
                                    else 'other' )
data['GPU_Name'].value_counts()

GPU_Name
Intel     722
Nvidia    400
AMD       180
other       1
Name: count, dtype: int64

In [20]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,Cpu_name,GPU_Name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,intel core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,intel core i5,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00,0,0,intel core i5,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1,intel core i7,AMD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1,intel core i5,Intel

In [21]:
# checking the categories of Opsys
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         27
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [22]:
# divide the operationg systems data 
data['Opsys_name'] = data['OpSys'].apply(lambda x:'Windows' if 'Windows' in x 
                                        else 'Linux' if 'Linux' in x
                                        else 'Mac' if 'Mac' or 'mac' in x 
                                        else 'other' )

In [23]:
# checking the cateogary types 
data['Opsys_name'].value_counts()

Opsys_name
Windows    1125
Mac         116
Linux        62
Name: count, dtype: int64

In [24]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,Cpu_name,GPU_Name,Opsys_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,intel core i5,Intel,Mac
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,intel core i5,Intel,Mac
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00,0,0,intel core i5,Intel,Mac
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1,intel core i7,AMD,Mac
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1,intel core i5,Intel,Mac

In [25]:
# drop the unwanted categaries
data = data.drop(columns = ['laptop_ID','Inches','ScreenResolution','Cpu','Gpu','OpSys','Product'])

In [26]:
data.head()

,Company,TypeName,Ram,Weight,Price_euros,Touchscreen,Ips,Cpu_name,GPU_Name,Opsys_name
0,Apple,Ultrabook,8,1.37,1339.69,0,1,intel core i5,Intel,Mac
1,Apple,Ultrabook,8,1.34,898.94,0,0,intel core i5,Intel,Mac
2,HP,Notebook,8,1.86,575.00,0,0,intel core i5,Intel,Mac
3,Apple,Ultrabook,16,1.83,2537.45,0,1,intel core i7,AMD,Mac
4,Apple,Ultrabook,8,1.37,1803.60,0,1,intel core i5,Intel,Mac

In [27]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      1303 non-null   str
 1   TypeName     1303 non-null   str
 2   Ram          1303 non-null   int32
 3   Weight       1303 non-null   float64
 4   Price_euros  1303 non-null   float64
 5   Touchscreen  1303 non-null   int64
 6   Ips          1303 non-null   int64
 7   Cpu_name     1303 non-null   str
 8   GPU_Name     1303 non-null   str
 9   Opsys_name   1303 non-null   str
dtypes: float64(2), int32(1), int64(2), str(5)
memory usage: 96.8 KB

In [28]:
# change the entire table into one hot encoding 
data = pd.get_dummies(data,dtype=int)

In [29]:
# check first 2 rows
data.head(2)

,Ram,Weight,Price_euros,Touchscreen,Ips,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,Cpu_name_intel core i3,Cpu_name_intel core i5,Cpu_name_intel core i7,GPU_Name_AMD,GPU_Name_Intel,GPU_Name_Nvidia,GPU_Name_other,Opsys_name_Linux,Opsys_name_Mac,Opsys_name_Windows
0,8,1.37,1339.69,0,1,0,1,0,0,0,...,0,1,0,0,1,0,0,0,1,0
1,8,1.34,898.94,0,0,0,1,0,0,0,...,0,1,0,0,1,0,0,0,1,0

In [30]:
data.shape

(1303, 32)

In [31]:
# divide the features as  x and y(output) value  
x = data.drop('Price_euros',axis=1)
y = data['Price_euros']

In [40]:
# divide the train and test values with test size into 0.25 
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(
    x, y, test_size=0.25
)

In [41]:
# make a function to output the model score 
def acc_score(model):
    model.fit(x_train,y_train)
    acc = model.score(x_test,y_test)
    print(str(model) + '-->' + str(acc))

In [42]:
# deciding the best regression model 
from sklearn.linear_model import LinearRegression 
lr = LinearRegression()
acc_score(lr)

from sklearn.linear_model import Lasso 
ls = Lasso()
acc_score(ls)

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
acc_score(dt)

from sklearn.ensemble import RandomForestRegressor 
rf = RandomForestRegressor()
acc_score(rf)

LinearRegression()-->0.6907372920335975
Lasso()-->0.688862888611776
DecisionTreeRegressor()-->0.6115844738690404
RandomForestRegressor()-->0.7653852412164925

In [43]:
# tuning hyper parameters 
from sklearn.model_selection import GridSearchCV

parameters = {'n_estimators':[10, 50, 100],
              'criterion':['squared_error','absolute_error','poisson']}

grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)

grid_fit = grid_obj.fit(x_train, y_train)

best_model = grid_fit.best_estimator_

best_model.score(x_test, y_test)

0.7621245134554834

In [44]:
# saving the model in a  pickle file 
import pickle 
with open('predictor.pickle','wb') as file:
    pickle.dump(best_model,file)

In [45]:
x_train.columns

Index(['Ram', 'Weight', 'Touchscreen', 'Ips', 'Company_Acer', 'Company_Apple',
       'Company_Asus', 'Company_Dell', 'Company_HP', 'Company_Lenovo',
       'Company_MSI', 'Company_Toshiba', 'Company_other',
       'TypeName_2 in 1 Convertible', 'TypeName_Gaming', 'TypeName_Netbook',
       'TypeName_Notebook', 'TypeName_Ultrabook', 'TypeName_Workstation',
       'Cpu_name_AMD', 'Cpu_name_Other', 'Cpu_name_intel core i3',
       'Cpu_name_intel core i5', 'Cpu_name_intel core i7', 'GPU_Name_AMD',
       'GPU_Name_Intel', 'GPU_Name_Nvidia', 'GPU_Name_other',
       'Opsys_name_Linux', 'Opsys_name_Mac', 'Opsys_name_Windows'],
      dtype='str')